name: CI
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./process
        steps:
            - uses: actions/checkout@v2
            - name: Build example
              run: |
                  git clone 'https://github.com/hunspell/hyphen.git'
                  cd hyphen
                  autoreconf -fvi
                  ./configure
                  make
                  make install
            - name: Install modules
              run: npm i
            - name: Run tests
              run: npm test
