name: CI
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./process
        steps:
            - uses: actions/checkout@v2
            - name: Install modules
              run: npm i
            - name: Run tests
              run: npm test
